const assert=require('node:assert/strict');
const path=require('node:path');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 try{
  const page=await browser.newPage({viewport:{width:1280,height:800}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('https://tile.openstreetmap.org/**',r=>r.abort());
  await require('./mock-roads.cjs')(page);
  await page.addInitScript(()=>Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(f){f({coords:{latitude:54.4,longitude:18.6}})}}}));
  await page.goto(process.env.MAP_URL||'file://'+path.resolve(__dirname,'../index.html'));
  assert.equal(await page.locator('[data-fraction]').count(),2,'Choose fractions independently, with no third combination option');
  assert.equal(await page.locator('select#fraction').count(),0);
  await page.locator('[data-fraction="electronics"]').click();
  assert.equal(await page.locator('[data-fraction][aria-pressed="true"]').count(),2);
  await page.locator('.pair-result').first().waitFor();
  const pairs=await page.evaluate(()=>pairsCurrent.map(p=>({key:p.key,total:p.total,gap:p.gap,stops:p.stops.map(s=>s.id)})));
  assert.equal(new Set(pairs.map(p=>p.key)).size,pairs.length);
  for(let i=1;i<pairs.length;i++)assert(pairs[i].total>=pairs[i-1].total);
  const before=await page.evaluate(()=>({center:[...view.center],zoom:view.zoom}));
  await page.locator('#pins [data-point]').first().waitFor();
  const markerId=await page.evaluate(()=>Number([...document.querySelectorAll('#pins [data-point]')].find(e=>{const r=e.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===e}).dataset.point));
  const marker=page.locator(`#pins [data-point="${markerId}"]`);
  const expectedPair=pairs.find(p=>p.stops.includes(markerId));
  await marker.click();
  assert.equal(await page.locator('#popup .popup-title').innerText(),'Oba podczas jednego przejazdu','Map markers open a pair when both fractions are selected');
  assert.equal(await page.evaluate(()=>selectedPair.key),expectedPair.key,'Choose the highest ranked pair containing the clicked point');
  await page.locator('#popup-close').click();
  assert.deepEqual(await page.evaluate(()=>({center:[...view.center],zoom:view.zoom})),before);
  await page.locator('.pair-result').first().click();
  assert.equal(await page.locator('#popup [data-pair-point]').count(),2);
  const chosen=await page.evaluate(()=>({origin:selectedPair.origin,stops:selectedPair.stops.map(p=>[p.geo.lat,p.geo.lon])}));
  const route=new URL(await page.locator('#pair-route').getAttribute('href'));
  assert.equal(route.searchParams.get('travelmode'),'driving');
  assert.equal(route.searchParams.get('origin'),chosen.origin.join(','));
  assert.equal(route.searchParams.get('waypoints'),chosen.stops[0].join(','));
  assert.equal(route.searchParams.get('destination'),chosen.stops[1].join(','));
  await page.waitForFunction(()=>document.querySelectorAll('.pin.pair-stop').length===2);
  assert.equal(await page.locator('.pin.pair-stop.textiles').count(),1);
  assert.equal(await page.locator('.pin.pair-stop.electronics').count(),1);
  await page.locator('#paths .pair-line').waitFor();
  assert.match(await page.locator('#popup').innerText(),/samochodem/);
  const pairKey=await page.evaluate(()=>selectedPair.key);
  await page.locator('.pin.pair-stop').first().click();
  assert.equal(await page.locator('#popup .popup-title').innerText(),'Oba podczas jednego przejazdu');
  assert.equal(await page.evaluate(()=>selectedPair.key),pairKey,'Clicking a selected stop preserves the current pair');
  await page.locator('#popup [data-pair-point]').first().click();
  assert(await page.locator('#back-to-pair').isVisible());
  await page.locator('#back-to-pair').click();
  assert(await page.locator('#pair-route').isVisible());
  await page.locator('#popup-close').click();
  assert.deepEqual(await page.evaluate(()=>({center:[...view.center],zoom:view.zoom})),before);
  const query=await page.evaluate(()=>pairsCurrent[0].stops[0].address_pdf);
  await page.locator('#search').fill(query);
  await page.locator('.pair-result').first().waitFor();
  await page.locator('#search').fill('nieistniejacy-adres-xyz');
  assert.equal(await page.locator('.pair-result').count(),0);
  await page.locator('#search').fill('');
  for(const width of [390,320]){
   await page.setViewportSize({width,height:844});
   await page.locator('#menu').click();
   await page.waitForFunction(()=>Math.abs(document.querySelector('.sidebar').getBoundingClientRect().x)<1);
   assert(await page.locator('.sidebar').evaluate(e=>e.scrollWidth<=e.clientWidth));
   await page.locator('.pair-result').first().click();
   assert(await page.locator('#popup').evaluate(e=>e.scrollWidth<=e.clientWidth));
   await page.waitForFunction(()=>document.querySelectorAll('.pin.pair-stop').length===2);
   const panel=await page.locator('#popup').boundingBox();
   for(const marker of await page.locator('.pin.pair-stop').all()){const box=await marker.boundingBox();assert(box.y+box.height<=panel.y,'Both stops stay above the mobile panel');}
   await page.locator('#popup-close').click();
  }
  await page.setViewportSize({width:1280,height:800});
  await page.locator('[data-fraction="textiles"]').click();
  assert.equal(await page.locator('.pair-result').count(),0);
  assert.equal(await page.locator('#visible-count').innerText(),'143');
  await page.locator('[data-fraction="electronics"]').click();
  assert.equal(await page.locator('#results .result').count(),0);
  assert.match(await page.locator('#results').innerText(),/Zaznacz/);
  assert.deepEqual(errors,[]);
  const waiting=await browser.newPage();
  await waiting.route('https://tile.openstreetmap.org/**',r=>r.abort());
  await require('./mock-roads.cjs')(waiting);
  await waiting.addInitScript(()=>Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(f){window.resolveGeo=()=>f({coords:{latitude:54.4,longitude:18.6}})}}}));
  await waiting.goto(process.env.MAP_URL||'file://'+path.resolve(__dirname,'../index.html'));
  await waiting.locator('[data-fraction="electronics"]').click();
  await waiting.locator('.pair-result').first().click();
  await waiting.waitForFunction(()=>document.querySelector('.pair-origin'));
  await waiting.evaluate(()=>window.resolveGeo());
  assert(await waiting.locator('#popup').isHidden(),'A newly received location dismisses a plan based on the old map center');
  assert.deepEqual(await waiting.evaluate(()=>view.center),[54.4,18.6]);
  await waiting.close();
 }finally{await browser.close()}
 console.log('PASS: independent multi-selection, nearby pair ranking/order, uncertainty safeguards, map links/markers, search, mobile, detail navigation and restored view');
})().catch(e=>{console.error(e);process.exit(1)});
