const assert=require('node:assert/strict');
const path=require('node:path');
const {chromium}=require('playwright');
const mockRoads=require('./mock-roads.cjs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 try{
  const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('https://tile.openstreetmap.org/**',r=>r.abort());
  await page.addInitScript(()=>Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(f){f({coords:{latitude:54.3375,longitude:18.576}})}}}));
  const mock=await mockRoads(page);mock.delay=300;
  await page.goto(process.env.MAP_URL||'file://'+path.resolve(__dirname,'../index.html'));
  assert.equal(mock.calls.length,0,'Single fraction does not query the routing service');
  await page.locator('[data-fraction="electronics"]').click();
  assert.match(await page.locator('#pair-hint').innerText(),/samochodem|autem/,'Replace the walking promise');
  assert.equal(await page.locator('.pair-result').count(),0,'Do not show straight-line estimates while waiting for road distances');
  await page.locator('.pair-result').first().waitFor();
  assert(mock.calls.some(u=>u.pathname.includes('/table/v1/driving/')));
  const before=await page.evaluate(()=>({center:[...view.center],zoom:view.zoom}));
  await page.locator('.pair-result').first().click();
  assert.equal(await page.locator('#popup .popup-title').innerText(),'Oba podczas jednego przejazdu');
  assert.equal(new URL(await page.locator('#pair-route').getAttribute('href')).searchParams.get('travelmode'),'driving');
  assert.equal(await page.locator('#paths .pair-line').count(),0,'Never draw a straight line while loading geometry');
  await page.locator('#paths .pair-line').waitFor();
  const d=await page.locator('#paths .pair-line').getAttribute('d');
  assert((d.match(/L/g)||[]).length>=4,'Draw all road geometry vertices, including detours');
  assert.equal(await page.locator('#paths .pair-line').getAttribute('stroke-dasharray'),null);
  assert.match(await page.locator('#popup').innerText(),/dojścia/,'Explain the last metres from the road');
  const requestCount=mock.calls.length;
  await page.locator('#popup-close').click();
  assert.deepEqual(await page.evaluate(()=>({center:[...view.center],zoom:view.zoom})),before);
  await page.locator('.pair-result').first().click();
  await page.locator('#paths .pair-line').waitFor();
  assert.equal(mock.calls.length,requestCount,'Reopening a route uses the cached result');
  await page.locator('#popup-close').click();
  mock.failRoute=true;
  await page.locator('.pair-result').nth(1).click();
  await page.locator('#retry-route').waitFor();
  assert.equal(await page.locator('#paths .pair-line').count(),0,'A service error must not become a straight route');
  mock.failRoute=false;await page.locator('#retry-route').click();await page.locator('#paths .pair-line').waitFor();
  await page.locator('#popup-close').click();
  mock.failMatrix=true;await page.locator('#search').fill('Gdynia');
  await page.locator('#retry-pairs').waitFor();assert.equal(await page.locator('.pair-result').count(),0);
  mock.failMatrix=false;await page.locator('#retry-pairs').click();await page.locator('.pair-result').first().waitFor();
  mock.delay=500;await page.locator('#search').fill('Sopot');
  await page.locator('[data-fraction="textiles"]').click();
  await page.waitForTimeout(800);
  assert.equal(await page.locator('.pair-result').count(),0,'A late response must not restore a dismissed mode');
  assert.equal(await page.locator('#popup').isHidden(),true);
  assert.deepEqual(errors,[]);
  console.log('PASS: car routing, road geometry, loading/errors/retry, cached routes, stale responses and restored view');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
