const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const source=html.match(/<script id="road-routing">([\s\S]*?)<\/script>/)?.[1];
assert(source,'Road routing must replace straight-line pair ranking');
const ctx=vm.createContext({URL,AbortController,DOMException,setTimeout,clearTimeout});
vm.runInContext(source,ctx);
const R=vm.runInContext('RoadRouting',ctx);
const p=(id,lat,source=false)=>({id,source:source?'city':undefined,geo:{status:'address',lat,lon:18}});
const t1=p(1,54.0001),t2=p(2,54.002),e=p(10,54.0002,true),points=[t1,t2,e];
const matrix={code:'Ok',distances:[[0,100,300,200],[100,0,500,5000],[300,500,0,350],[200,5000,400,0]],sources:[0,1,2,3].map(()=>({distance:0}))};
let pairs=R.rank(points,matrix,[54,18],()=>true);
assert.equal(pairs[0].key,'2:10','A close point across a barrier loses to a longer straight-line distance with a shorter drive');
assert.equal(pairs[0].total,600);
assert.equal(pairs[0].stops[0].id,10,'Compare directed routes in both visit orders');
assert.equal(pairs[0].gap,400);
matrix.distances[3][2]=null;
pairs=R.rank(points,matrix,[54,18],()=>true);
assert.equal(pairs[0].stops[0].id,2,'An unreachable direction must not become zero metres');
assert.equal(pairs[0].total,650);
matrix.sources[2].distance=300;
pairs=R.rank(points,matrix,[54,18],()=>true);
assert.equal(pairs[0].key,'1:10','Do not claim a road hundreds of metres away reaches the point');
matrix.sources[0].distance=500;
assert.equal(R.rank(points,matrix,[54,18],()=>true).length,0,'Do not silently relocate the origin far away');
const textiles=Array.from({length:100},(_,i)=>p(i+1,54+i/1000));
const electronics=Array.from({length:100},(_,i)=>p(i+1001,54+i/1000,true));
textiles.push({id:2000,geo:{status:'unresolved'}},{id:2001,geo:{status:'approx',lat:54,lon:18,area_only:true}});
let candidates=R.candidates(textiles,electronics,[54,18],()=>true);
assert(candidates.length<=72,'Bound the matrix rather than sending the whole province');
assert(candidates.every(p=>p.id!==2000&&p.id!==2001));
candidates=R.candidates(textiles,electronics,[54,18],p=>p.id===1100);
assert(candidates.some(p=>p.id===1100),'A search for a remote point must include that point');
assert(candidates.some(p=>!p.source&&p.id>=98),'Search also includes partners near that remote point');
console.log('PASS: road distances, directional visit order, unreachable roads, snapping limits, bounded candidates and remote address search');
(async()=>{
 const storage=new Map();let calls=[],bad=false;
 const response={code:'Ok',distances:[[0,100,200,300],[100,0,200,300],[200,200,0,300],[300,300,300,0]],sources:Array.from({length:4},()=>({distance:0}))};
 function client(){
  const context=vm.createContext({URL,AbortController,DOMException,setTimeout,clearTimeout,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},fetch:async(url,options)=>{calls.push({url,at:Date.now()});return{ok:true,json:async()=>bad?{code:'Ok'}:response}}});
  vm.runInContext(source,context);return vm.runInContext('RoadRouting',context);
 }
 let client1=client();await client1.matrix(points,[54,18]);await client1.matrix(points,[54,18]);
 assert.equal(calls.length,1,'Reuse a matrix without sending the origin again');
 await client().matrix(points,[54,18]);assert.equal(calls.length,1,'The cache survives a page reload');
 const controller=new AbortController();controller.abort();
 await assert.rejects(client1.matrix(points,[54.01,18],controller.signal),{name:'AbortError'});
 assert.equal(calls.length,1,'An aborted request never sends coordinates');
 storage.clear();calls=[];client1=client();
 await Promise.all([client1.matrix(points,[54.02,18]),client1.matrix(points,[54.03,18])]);
 assert(calls[1].at-calls[0].at>=1000,'Respect the provider limit of one request per second');
 bad=true;await assert.rejects(client1.matrix(points,[54.04,18]),/Niepełne/);
 bad=false;const count=calls.length;await client1.matrix(points,[54.04,18]);
 assert.equal(calls.length,count+1,'Do not cache malformed successful responses');
 console.log('PASS: persistent cache, cancellation, rate limiting and retry after invalid responses');
})().catch(e=>{console.error(e);process.exit(1)});
